// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxtSOrTe6x57rJ11E0BDEZLtdny0UQwWs',
    appId: '1:211144366461:web:7ef04122e274445fee5414',
    messagingSenderId: '211144366461',
    projectId: 'stor-shooping',
    authDomain: 'stor-shooping.firebaseapp.com',
    storageBucket: 'stor-shooping.firebasestorage.app',
    measurementId: 'G-9SPKFMFGHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9aaDq7QbTNQC-OmRdW5x4OZ8UQxxGv4',
    appId: '1:211144366461:android:e0d40b547f84170aee5414',
    messagingSenderId: '211144366461',
    projectId: 'stor-shooping',
    storageBucket: 'stor-shooping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcFVv_1p5Nnfa_2gQkF-CxtofbBB6zz8',
    appId: '1:211144366461:ios:53c36ef3e3f5d2ecee5414',
    messagingSenderId: '211144366461',
    projectId: 'stor-shooping',
    storageBucket: 'stor-shooping.firebasestorage.app',
    iosBundleId: 'com.example.storsAdminPanel',
  );
}
